[ -z "$PS1" ] && return; # don't do anything if not running interactively

set -o emacs;            # Force Bash's Emacs Mode

shopt -s checkwinsize    # check (& update) window size after every command
shopt -s histappend      # append to history file, don't overrite

HISTCONTROL=ignoreboth   # no duplicate lines, lines starting with space
HISTFILESIZE=1000        # max num of lines
HISTSIZE=100             # max num of commands

! [ -d "$HOME/.bash" ] && return;   # Early exit if ~/.bash doesn't exit


## Bash Extensions
DIRS="export source alias";

for dir in $DIRS;
do
    [ -d "$HOME/.bash/$dir" ]  && . "$HOME/.bash/$dir"/*.sh;
done

unset DIRS
